Feature/orb 64 agent group creation endpoint
ns1labs/orb pull request #107
Opened 2021-08-12 21:06 UTC by mclcavalcante

feat(agent_group): Agent group creation resource

2021-08-12 21:45 UTC, dscabral requested changes

2021-08-12 21:45 UTC, dscabral commented on fleet/agent_group_service_test.go
> +		Created:     time.Time{},
For validate, this Created it's not necessary

2021-08-12 21:45 UTC, dscabral commented on fleet/agent_service.go
> +}
Should remove, it's not part of this issue.

2021-08-12 21:45 UTC, dscabral commented on fleet/api/endpoint.go
> +			created: true,
Should not return created, if we're just validating.

2021-08-12 21:45 UTC, dscabral commented on fleet/api/logging.go
> +func (l loggingMiddleware) ValidateAgent(ctx context.Context, token string, a fleet.Agent) (_ fleet.Agent, err error) {
Remove this validate agent

2021-08-12 21:45 UTC, dscabral commented on fleet/api/metrics.go
> +func (m metricsMiddleware) ValidateAgent(ctx context.Context, token string, a fleet.Agent) (fleet.Agent, error) {
Remove this validate agent

2021-08-12 21:45 UTC, dscabral commented on fleet/api/openapi.yaml
> +        '409':
Remove this error, it will not conflict.

2021-08-12 21:45 UTC, dscabral commented on fleet/api/openapi.yaml
> +        '422':
Remove this error, it will not make a query on db.

2021-08-12 21:45 UTC, dscabral commented on fleet/api/responses.go
> +	created        bool
Don't need created and TsCreated fields for this struct

2021-08-12 21:45 UTC, dscabral commented on fleet/api/responses.go
> +type validateAgentRes struct {
Remove this struct

2021-08-12 21:45 UTC, dscabral commented on fleet/mocks/agent_groups.go
> +
Its not necessary any more

2021-08-12 21:45 UTC, dscabral commented on fleet/redis/producer/streams.go
> +func (es eventStore) ValidateAgent(ctx context.Context, token string, a fleet.Agent) (fleet.Agent, error) {
Remove this function

2021-08-13 18:19 UTC, dscabral requested changes

2021-08-13 18:19 UTC, dscabral commented on fleet/api/responses.go
> +	TsCreated      time.Time      `json:"ts_created,omitempty"`
We don't need this TsCreated on validateRes

2021-08-13 21:19 UTC, dscabral approved these changes

2021-08-13 22:47 UTC, dscabral approved these changes

2021-08-13 23:02 UTC, dscabral submitted a review, later dismissed

2021-08-17 13:48 UTC, weyrick commented on fleet/agent_group_service.go
> +
I thought the goal here was also to return the number of matching agents?

2021-08-18 14:05 UTC, weyrick commented on fleet/postgres/agents.go
> +	t, tmq, err := getOrbTagsQuery(tags)
To be clear, whenever we are matching an agent group to agents, it must match against _both_ `agents.agent_tags` and `agents.orb_tags` - is that what we are doing here and in the other calls? You will see that the query for the `agent_group_membership` does this, for example.

2021-08-18 14:08 UTC, weyrick requested changes

2021-08-18 14:08 UTC, weyrick commented on fleet/postgres/agents.go
> +			from agents WHERE mf_thing_id is not null %s) as agent_groups`, tmq)
security problem: this query does not limit for OwnerID so it will query agents from all tenants

2021-08-18 19:05 UTC, weyrick approved these changes

2021-08-19 18:17 UTC, weyrick approved these changes

2021-08-19 20:35 UTC, dscabral approved these changes

2021-08-19 23:05 UTC, merged