Tests/randomized tags
ns1labs/orb pull request #1148
Opened 2022-04-29 19:30 UTC by manrodrigues

Randomizing tags to avoid conflicts when scenarios run in parallel

2022-05-03 17:08 UTC, leoparente submitted a review, later dismissed

2022-05-04 14:19 UTC, lpegoraro requested changes
Just one comment, to be more maintainable.

2022-05-04 15:06 UTC, manrodrigues commented on python-test/features/steps/utils.py
> +        if re.match(r"^.+\:.+", orb_tags):
I inserted a comment and improved the assertion message.. please, check

2022-05-04 18:14 UTC, lpegoraro approved these changes
LGTM

2022-05-04 19:10 UTC, merged