fix(policy): fix reapply policy after the dataset becomes valid again
ns1labs/orb pull request #1202
Opened 2022-05-18 21:27 UTC by mclcavalcante

fix reapplying policy when the dataset becomes valid again after the sink which was linked is removed and a new one is added

2022-05-19 19:51 UTC, lpegoraro submitted a review, later dismissed
LGTM

2022-05-20 21:19 UTC, weyrick requested changes
see thread https://ns1labs.slack.com/archives/C01UNG6UK37/p1653071246986939

2022-06-13 18:27 UTC, lpegoraro approved these changes
LGTM

2022-06-14 16:05 UTC, weyrick requested changes

2022-06-14 16:26 UTC, weyrick requested changes

2022-06-14 16:26 UTC, weyrick commented on policies/redis/producer/events.go
> +}
see my other comment: add `valid`, `turnedValid`, `turnedInvalid`

2022-06-14 16:26 UTC, weyrick commented on fleet/comms.go
> +	if dataset.Valid {
change to TurnedValid

2022-06-14 16:26 UTC, weyrick commented on fleet/comms.go
> +	dataset, err := svc.policyClient.RetrieveDataset(ctx, &pb.DatasetByIDReq{
we shouldn't need to call this, it should get all information it needs from the redis stream

2022-06-23 08:38 UTC, weyrick requested changes
almost there, one minor optimization and i think we are ready

2022-06-23 08:38 UTC, weyrick commented on fleet/redis/consumer/streams.go
> +	ag, err := es.fleetService.ViewAgentGroupByIDInternal(ctx, e.agentGroupID, e.ownerID)
this should be done in the block below so that we avoid a database lookup unless we really need it

2022-06-24 13:55 UTC, weyrick approved these changes

2022-07-01 19:51 UTC, merged