Feature/orb 1300 add policy status agent list
ns1labs/orb pull request #1318
Opened 2022-06-08 22:25 UTC by mclcavalcante

Adds the following map structure field to response of agent list endpoint, in which the key is the policy ID and the value is the policy information. All retrieve from lastHBData on DB

``
   "policy_status": {
      "43230fb0-9b28-d73c-0d40-efc8446bcfe8":{
          "name": "test",
          "status": "running"
      }
   }
``

2022-06-09 21:22 UTC, lpegoraro approved these changes
LGTM

2022-06-09 21:24 UTC, lpegoraro commented
@mclcavalcante Add a print of it running locally in the Network tab in the Web Console of the Browser or from Postman, that ensures and it is easier on the code reviewer

2022-06-13 22:01 UTC, weyrick requested changes

2022-06-13 22:01 UTC, weyrick commented on fleet/api/http/endpoint.go
> +	"github.com/mitchellh/mapstructure"
why are we using this instead of JSON decode?

2022-06-14 17:26 UTC, lpegoraro commented on fleet/api/http/endpoint.go
> +				return nil, err
We will extract the method into the service that's better either way

2022-06-23 08:23 UTC, weyrick requested changes

2022-06-23 08:23 UTC, weyrick commented on fleet/agent_service.go
> +		svc.logger.Error("failed to marshal heartbeat data", zap.Error(err))
need to return here on error so it doesn't continue

2022-06-23 08:23 UTC, weyrick commented on fleet/agent_service.go
> +		svc.logger.Error("failed to unmarshal heartbeat data", zap.Error(err))
same here

2022-06-24 13:57 UTC, weyrick approved these changes

2022-06-28 19:06 UTC, merged