Feature/orb agent delete
ns1labs/orb pull request #160
Opened 2021-08-19 20:30 UTC by lterranova

Resolves #135 #136 #137

2021-08-20 20:55 UTC, dscabral requested changes

2021-08-20 20:55 UTC, dscabral commented on fleet/api/logging.go
> +func (l loggingMiddleware) RemoveAgent(ctx context.Context, owner, id string) (err error) {
Here, the second param it's token, not owner

2021-08-20 20:55 UTC, dscabral commented on fleet/api/metrics.go
> +func (m metricsMiddleware) RemoveAgent(ctx context.Context, owner string, id string) error {
Here, the second param it's token, not owner

2021-08-20 20:55 UTC, dscabral commented on fleet/postgres/agents_test.go
> +		"remove a non-existing agent": {
Here you need to pass a invalid MFThingID

2021-08-20 20:55 UTC, dscabral commented on fleet/redis/producer/events.go
>  	AgentGroupRemove = AgentGroupPrefix + "remove"
Why are you creating this redis stream call?

2021-08-20 20:55 UTC, dscabral commented on fleet/redis/producer/events.go
> +
I don't think we need to send a message to redis stream

2021-08-20 20:55 UTC, dscabral commented on fleet/redis/producer/streams.go
> +func (es eventStore) RemoveAgent(ctx context.Context, token, id string) (err error) {
Same here

2021-08-23 22:27 UTC, dscabral requested changes

2021-08-23 22:27 UTC, dscabral commented on fleet/mocks/things.go
> +	return nil
Here has to be implemented the remove function

2021-08-23 22:27 UTC, dscabral commented on fleet/mocks/agent.go
> +func (a agentRepositoryMock) Delete(ctx context.Context, owner, thingID string) error {
Use ownerID to maintain the consistency

2021-08-23 22:27 UTC, dscabral commented on fleet/agents.go
> +	Delete(ctx context.Context, owner string, thingID string) error
Use ownerID to maintain the consistency

2021-08-24 21:26 UTC, dscabral requested changes

2021-08-24 21:26 UTC, dscabral commented on fleet/mocks/things.go
> +	delete(svc.channels, key(owner, id))
Change the delete(svc.channels, key(owner, id)) to delete(svc.channels, id)

2021-08-26 21:46 UTC, dscabral submitted a review, later dismissed

2021-09-03 18:53 UTC, weyrick requested changes

2021-09-03 18:53 UTC, weyrick commented on fleet/agent_service.go
> +		svc.logger.Error("failed to delete thing", zap.Error(errT))
Sorry forgot to mention this but please include res.MFThingID as a logger variable, like this:
```
svc.logger.Error("failed to delete thing", zap.Error(errT), zap.String('thing_id', res.MFThingID))
```

2021-09-03 18:53 UTC, weyrick commented on fleet/agent_service.go
> +		svc.logger.Error("failed to delete channel", zap.Error(errT))
and same here, including channel id

2021-09-07 15:06 UTC, weyrick approved these changes
🎉

2021-09-08 11:26 UTC, merged