feat(sinker): prepare methods to export YAML configuration based on s…
ns1labs/orb pull request #1848
Opened 2022-10-04 19:24 UTC by lpegoraro

…tore configuration of each sink

- [ ] Add unit tests
- [ ] Compare YAML files

Signed-off-by: Luiz Pegoraro <luiz.pegoraro@encora.com>

2022-10-10 16:45 UTC, lpegoraro commented
Integrated tests shown we need update
- [ ] Remove any quote in receiver, exporter list
- [ ] Kafka Topic doesnt allow slash

2022-10-11 13:13 UTC, etaques requested changes

2022-10-11 14:27 UTC, lpegoraro commented on sinker/config_builder.go
> +func ReturnConfigYamlFromSink(_ context.Context, kafkaUrlConfig, sinkId, sinkUrl, sinkUsername, sinkPassword string) (string, error) {
for now, we are ok, I will handle that in #1609

2022-10-11 20:23 UTC, weyrick approved these changes

2022-10-11 20:23 UTC, weyrick commented on sinker/config_builder.go
> +func ReturnConfigYamlFromSink(_ context.Context, kafkaUrlConfig, sinkId, sinkUrl, sinkUsername, sinkPassword string) (string, error) {
agreed this needs to be more flexible in the future (even prometheus may have a different authentication method than user name and password) but this is probably ok to start

2022-10-12 18:19 UTC, etaques approved these changes

2022-10-17 14:09 UTC, merged