Feature/orb openapi policy
ns1labs/orb pull request #213
Opened 2021-08-30 20:39 UTC by lterranova

Resolves #212

2021-09-22 13:24 UTC, dscabral requested changes

2021-09-22 13:24 UTC, dscabral commented on policies/api/openapi.yaml
> +            value: "version: \"1.0\"\nvisor:\n    foo: \"bar\""
Only policy_data has a yaml format, policy it's a json, you should change do json format

2021-09-22 13:24 UTC, dscabral commented on policies/api/openapi.yaml
> +        sink_id:
sink_id should be an array of strings

2021-09-22 13:24 UTC, dscabral commented on policies/api/openapi.yaml
> +        sink_id:
Should be an array of strings

2021-09-22 13:24 UTC, dscabral commented on policies/api/openapi.yaml
> +        sink_id:
Should be an array of strings

2021-09-23 17:26 UTC, dscabral approved these changes

2021-09-23 23:38 UTC, weyrick approved these changes
Ok I think this is ok to land now, but be aware that in the future we may accept a policy format other than `yaml` so we will have to update the docs at that point.

2021-09-24 13:18 UTC, merged