Feature/orb 207 policy validation endpoint
ns1labs/orb pull request #224
Opened 2021-09-03 20:36 UTC by mclcavalcante

resolves #207

2021-09-13 18:06 UTC, dscabral requested changes

2021-09-13 18:06 UTC, dscabral commented on policies/policy_service.go
> +	if !backend.HaveBackend(p.Backend) {
The code between the line 213 and 230 was extracted to a function called validatePolicyBackend, please check on policy_service file and the functions.

You can use with the example below
```err = validatePolicyBackend(p, format, policyData)```

2021-09-13 21:13 UTC, dscabral approved these changes

2021-09-15 15:39 UTC, weyrick approved these changes

2021-09-15 16:49 UTC, merged