Feature/orb create policies
ns1labs/orb pull request #225
Opened 2021-09-06 19:00 UTC by lterranova

Resolves #202

2021-09-08 19:22 UTC, gpazuch commented
I have no idea of how this conflict came into existence.
I'll take a look into it

2021-09-13 18:20 UTC, dscabral requested changes

2021-09-13 18:20 UTC, dscabral commented on policies/api/http/endpoint_test.go
> +	// validJson         = "{ \"name\": \"my-policy\", \"description\": \"A policy example\", \"tags\": { \"region\": \"eu\", \"node_type\": \"dns\" }, \"backend\": \"pktvisor\", \"policy\": {\n  \"vers
It's unused const? If it will not be used, please remove it.

2021-09-13 18:20 UTC, dscabral commented on policies/api/http/endpoint_test.go
> +	validYaml         = `{"name": "mypktvisorpolicyyaml-3", "backend": "pktvisor", "description": "my pktvisor policy yaml", "tags": {"region": "eu", "node_type": "dns"}, "format": "yaml","policy_data":
Give a more significant name to this const... for example validPolicyDataJson and validPolicyDataYaml

2021-09-13 18:20 UTC, dscabral commented on policies/api/openapi.yaml
>            content:
Use the openapi PR to this change... rollback the openapi.yaml file as the develop with the command below
❯ git checkout origin/develop policies/api/openapi.yaml

2021-09-14 21:42 UTC, dscabral approved these changes

2021-09-15 15:43 UTC, weyrick submitted a review, later dismissed

2021-09-16 18:48 UTC, weyrick requested changes

2021-09-16 18:48 UTC, weyrick commented on policies/api/http/endpoint_test.go
> +	validPolicyDataJson = "{ \"name\": \"simple_dns\", \"backend\": \"pktvisor\", \"policy\": { \"version\": \"1.0\", \"visor\": { \"policies\": { \"mydefault\": { \"input\": {\"tap\": \"mydefault\"}, \
can you use this instead please? the format has changed slightly now
```
{
    "name": "simple_dns",
    "backend": "pktvisor",
    "policy": {
        "kind": "collection",
        "input": {
            "tap": "mydefault",
            "input_type": "pcap"
        },
        "handlers": {
            "modules": {
                "default_net": {
                    "type": "net"
                },
                "default_dns": {
                    "type": "dns"
                }
            }
        }
    }
}
```

2021-09-16 18:48 UTC, weyrick commented on policies/api/http/endpoint_test.go
> +	validPolicyDataYaml = `{"name": "mypktvisorpolicyyaml-3", "backend": "pktvisor", "description": "my pktvisor policy yaml", "tags": {"region": "eu", "node_type": "dns"}, "format": "yaml","policy_data
let's make "policy_data" in the yaml this: `handlers:\n  modules:\n    default_dns:\n      type: dns\n    default_net:\n      type: net\ninput:\n  input_type: pcap\n  tap: mydefault\nkind: collection`

2021-09-20 15:24 UTC, weyrick approved these changes

2021-09-20 15:27 UTC, merged