Feature/orb read datasets
ns1labs/orb pull request #334
Opened 2021-09-23 21:50 UTC by mclcavalcante

Resolves #273

2021-09-29 15:10 UTC, dscabral requested changes

2021-10-01 17:34 UTC, dscabral submitted a review, later dismissed

2021-10-04 18:23 UTC, weyrick requested changes

2021-10-04 18:23 UTC, weyrick commented on policies/api/http/logging.go
> +			l.logger.Warn("method call: list_dataset_by_groups",
should this be `list_dataset_by_policy_internal` as per the function name?

2021-10-04 18:23 UTC, weyrick commented on policies/api/http/logging.go
> +	return l.svc.ListDatasetsByPolicyIDInternal(ctx, policyID, ownerID)
this seems to be calling a different function, where  `Datasets` is plural with an s, seems like that maybe a typo, or at least an inconsistency?

2021-10-04 18:23 UTC, weyrick commented on policies/api/http/transport.go
> +		kitot.TraceServer(tracer, "view_policy")(viewDatasetEndpoint(svc)),
`view_dataset` instead of `view_policy`

2021-10-04 18:23 UTC, weyrick commented on policies/api/http/transport.go
> +		kitot.TraceServer(tracer, "list_dataset")(listDatasetEndpoint(svc)),
`list_datasets` plural for consistency

2021-10-04 18:23 UTC, weyrick commented on policies/api/http/responses.go
> +	Dataset []datasetRes `json:"dataset"`
`Datasets` plural for consistency with arrays

2021-10-04 18:23 UTC, weyrick commented on policies/policies.go
> +	ListDataset(ctx context.Context, token string, pm PageMetadata) (PageDataset, error)
I think this should also be plural `ListDatasets`

2021-10-04 18:23 UTC, weyrick commented on policies/policies.go
> +	RetrieveAllDatasetByOwner(ctx context.Context, ownerID string, pm PageMetadata) (PageDataset, error)
`RetrieveAllDatasetsByOwner`

2021-10-04 20:08 UTC, weyrick approved these changes

2021-10-04 20:17 UTC, merged