fix(orb-ui): fix agent provisioning command
ns1labs/orb pull request #421
Opened 2021-11-02 20:40 UTC by gpazuch

closes #418 
Fix agent provisioning command

2021-11-02 20:45 UTC, weyrick requested changes

2021-11-02 20:45 UTC, weyrick commented on ui/src/app/pages/fleet/agents/key/agent.key.component.ts
> +    this.command2copy = `docker run --rm --net=host \
this needs to add `-d` as per https://github.com/ns1labs/orb/issues/418

2021-11-02 20:45 UTC, weyrick commented on ui/src/app/pages/fleet/agents/key/agent.key.component.ts
> +-e PKTVISOR_PCAP_IFACE_DEFAULT=\$\{PKTVISOR_IFACE\} \
what is `\$\{PKTVISOR_IFACE\}` ?

2021-11-02 20:45 UTC, weyrick commented on ui/src/app/pages/fleet/agents/key/agent.key.component.ts
> +-e ORB_CLOUD_MQTT_ID='${ this.agent.id }' \
let's get rid of single quotes here and for channel and key

2021-11-03 12:26 UTC, gpazuch reviewed
@weyrick command should be ok now

2021-11-03 13:39 UTC, weyrick approved these changes

2021-11-03 13:51 UTC, merged