doc(fleet): openapi spec update
ns1labs/orb pull request #443
Opened 2021-11-04 19:04 UTC by mclcavalcante

add routes:

- /agents/backends/agents 
- /agents/backends/pktvisor/taps 
- /agents/backends/pktvisor/inputs 
- /agents/backends/pktvisor/handlers 
- /agents/backends/{backend}/

2021-11-05 20:26 UTC, dscabral requested changes
After this, you can land this review to Shannon

2021-11-05 20:26 UTC, dscabral commented on fleet/api/http/openapi.yaml
> +  /agents/backends/{backend}/:
It's necessary the slash on the end

2021-11-08 17:21 UTC, weyrick commented on fleet/api/http/openapi.yaml
> +      summary: 'List of Taps available from current agents'
let's make this description very pktvisor specific: "List of pktvisor Taps available from current agents"

2021-11-08 17:22 UTC, weyrick commented on fleet/api/http/openapi.yaml
> +      summary: 'List of Inputs available across current agents'
same, "List of pktvisor Inputs..."

2021-11-08 17:22 UTC, weyrick commented on fleet/api/http/openapi.yaml
> +      summary: 'List of Handlers available across current agents'
"List of pktvisor Handlers..."

2021-11-08 18:13 UTC, weyrick approved these changes

2021-11-09 16:53 UTC, dscabral approved these changes

2021-11-09 16:55 UTC, merged