Refact/orb dataset agent architecture
ns1labs/orb pull request #562
Opened 2021-11-22 20:05 UTC by dscabral

Resolves #449

2021-11-22 23:50 UTC, dscabral commented on go.mod
> +	github.com/fullstorydev/grpcurl v1.8.5 // indirect
Remove it before PR

2021-11-22 23:50 UTC, dscabral commented on buildinfo/version.go
> +var version = "0.9.0-develop"
Version should be "unknown"

2021-11-23 16:43 UTC, weyrick requested changes
Looks pretty good but I realized one important thing here: we still need to be producing and consuming dataset removed redis events, so we need to leave that code in. However, now instead of the fleet consumer calling `NotifyGroupDatasetRemoval`, it's got to run some logic to see if it should send `AgentPolicyRPCPayload` with "remove" action to tell the agent(s) to stop running that policy. Essentially we have moved the complexity from the agents into this one function. If we don't do this, there is no way an agent would know to stop running a policy when a dataset is deleted. However, since there maybe overlap between policies and datasets, we can't just send `AgentPolicyRPCPayload` "remove" until we check that no other datasets want that policy to run. Let's discuss.

2021-11-23 16:43 UTC, weyrick commented on policies/pb/policies.proto
> +  bool valid = 4;
now that we will have our first users and production environments, we need to start thinking about backwards compatibility here - I'm pretty sure you should never change a field's number, you can only add new ones. we should read up on this

https://earthly.dev/blog/backward-and-forward-compatibility/
https://developers.google.com/protocol-buffers/docs/proto3#assigning_field_numbers

2021-12-22 14:46 UTC, weyrick commented
I recommend we close this for now. You can save the branch if you want for reference though, when we get around to looking at this problem again

2021-12-27 13:29 UTC, closed without merging